### ISSUE TITLE
RequestVatInfo response: OracleConnection.ConnectionString is invalid (all of a sudden)

### ISSUE THREAD

**Issue by imneckro** [firebed/aade-mydata#17]
Hello.
All of a sudden in RequestVatInfo  I am getting:
Client error: `GET https://mydatapi.aade.gr/myDATA/RequestVatInfo?dateFrom=01%2F02%2F2024&dateTo=29%2F02%2F2024` resulted in a `400 Bad Request` response: OracleConnection.ConnectionString is invalid

**Comment by firebed** [comment]
It's probably a mydata issue. Please wait until the issue is resolved by itself.

**Comment by imneckro** [comment]
Still aade tromparei....
8 RequestVatInfo out of 10 are failure (Bad Request response: OracleConnection.ConnectionString is invalid).

**Comment by firebed** [comment]
Thanks for letting me know. I am closing this issue since it is not related to this repository.
