### ISSUE TITLE
Χρήση PHP8.1 enums

### ISSUE THREAD

**Issue by bugos** [firebed/aade-mydata#2]
Καταρχάς συγχαρητήρια για την πολύ καλή δουλειά και ευχαριστούμε που τη μοιραστήκατε.

Θα ήθελα να ρωτήσω αν θα ήσασταν θετικοί στην μετατροπή των κλάσεων στον φάκελο enums σε [PHP 8.1 enumerations](https://www.php.net/manual/en/language.enumerations.backed.php), έτσι ώστε να μπορούν να χρησιμοποιηθούν οι μέθοδοι ```from(int|string)``` και ```tryFrom(int|string)``` που αναφέρονται στο link.

**Comment by firebed** [comment]
Καλησπέρα, έχει ήδη ολοκληρωθεί η έκδοση 2 που είναι συμβατή με php 8.1 και έχει εκσυγχρονιστεί με το myDATA v1.0.4. Πέρα από κάποια bug fixes η έκδοση αυτή χρεισιμοποεί enum cases αντί για constants και magic properties/methods αντί για getters/setters. Θα δημοσιευθεί μόλις ολοκληρωθούν οι δοκιμές.

**Comment by bugos** [comment]
Καλησπέρα,
Ήθελα να ρωτήσω αν υπάρχει πρόοδος με την νέα έκδοση. Αν υπάρχει κάποιο κομμάτι που μπορώ να βοηθήσω η να τεστάρω, θα χαρώ να βοηθήσω.

**Comment by firebed** [comment]
Έχει εκδοθεί η έκδοση v2.0.0.
Αν εντοπίσετε σφάλματα ή προτείνετε κάποια βελτοποίηση παρακαλώ μην διστάσετε για pr.
