### ISSUE TITLE
$request = new RequestVatInfo() no longer returns Mark

### ISSUE THREAD

**Issue by imneckro** [firebed/aade-mydata#20]
Hello.
After update $request = new RequestVatInfo(); no longer returns Mark number.

**Comment by isarantoglou** [comment]
Hi @imneckro,

After the update to v5.0 and according to the upgrade guide (https://github.com/firebed/aade-mydata/blob/5.x/docs/upgrade-guide.md) 

> Removed vat-registry dependency from composer. You can include vat-registry by running composer require firebed/vat-registry. [See vat-registry](https://github.com/firebed/vat-registry) documentation for more information.

So you just need to run 

> composer require firebed/vat-registry

**Comment by imneckro** [comment]
This has nothing to do with vat registry.

RequestVatInfo() used to return "Mark".

Now it doesn't return "Mark".

**Comment by firebed** [comment]
Hi you need to set the `groupedPerDay` parameter to `false`.

```php
$request = new RequestVatInfo();
$response = $req->handle('01/01/2024', '31/12/2024', groupedPerDay: false);
```

**Comment by firebed** [comment]
This parameter was introduced in v5 and now that I rethink about it, it feels like it should default to false. So I am planning to make a new release with the groupedPerDay param set to false for backward compatibility. Thank you for bringing this to my attention.

**Comment by firebed** [comment]
Issue fixed. See release https://github.com/firebed/aade-mydata/releases/tag/v5.1.0
